---
- name: Ensure Jenkins is started and enabled
  service:
    name: jenkins
    state: started
    enabled: yes

- name: Wait for Jenkins HTTPS to start up
  uri:
    url: "https://localhost:{{ jenkins_https_port }}{{ jenkins_context_path }}/cli/"
    status_code: 403
    timeout: 5
    validate_certs: false
  register: result
  until: result.status == 403
  retries: 60
  delay: 5
  when: jenkins_enable_ssl | bool