---

- name: start jenkins
  service:
    name: jenkins
    state: started
  listen: "start jenkins"

- name: enable jenkins
  service:
    name: jenkins
    state: enabled
  listen: "enable jenkins"

- name: restart jenkins
  service:
    name: jenkins
    state: restarted
  listen: "restart jenkins"

- name: reload jenkins
  service:
    name: jenkins
    state: reloaded
  listen: "reload jenkins"